name       : pocillo-gtk-theme
version    : '0.10'
release    : 3
source     :
    - https://github.com/UbuntuBudgie/pocillo-gtk-theme/archive/refs/tags/v0.10.tar.gz : c8085c9feafe60f97c5683b0e9e34110a3f87d812115e3c64bdbb0938d508e33
homepage   : https://github.com/UbuntuBudgie/pocillo-gtk-theme
license    : GPL-2.0-or-later
component  :
    - desktop.theme
    - slim : desktop.theme
summary    : Material Design GTK Theme
description: |
    GTK based theme for the Budgie Desktop that has Material Design elements and styled using the Arc colour palette.
networking : yes
builddeps  :
    - pkgconfig(gtk4)
    - sassc
    - nodejs
rundeps    :
    - gtk-engines
    - gtk2-engine-murrine
    - slim :
        - pocillo-gtk-theme
patterns   :
    - slim : /usr/share/themes/*slim*
setup      : |
    %meson_configure -Dtheme_name=Pocillo
build      : |
    %ninja_build
install    : |
    %ninja_install
    rm -rf $installdir/usr/share/themes/*/{COPYING,INSTALL_GDM_THEME.md}
